### ISSUE TITLE
Can't join any servers with this mod

### ISSUE THREAD

**Issue by AkumaNoTenshi** [jakemaguy/QuickBuyMenu#12]
I love the mod. It's one of my most favorite mods. The only downside is I can't seem to join anyone with the mod. Don't know if this is a bug or if it's meant to be like this.

**Comment by jakemaguy** [comment]
Thank you I'm glad you're enjoying the mod.

The mod is server side, so it requires everyone to also have the mod installed.

**Comment by AkumaNoTenshi** [comment]
I thought so but still wasn't sure. Thanks for the response. I hope your mod continues to grow.
