### ISSUE TITLE
New feature request: quick buying multiple items

### ISSUE THREAD

**Issue by GuavaLavaa** [jakemaguy/QuickBuyMenu#14]
Hey, I think this mod is good but could actually be amazing with what seems like a small change. Normally to order 4 shovels you would have type "shov 4". Currently, I believe you can only buy one item at a time with this mod. This mod could make everything SO much faster by letting you type "qb shov 4" (all in one command) and have all four shovels in your inventory instantly. If the player ordered too many items to fit in their inventory, have the rest drop on the ground next to that player. If something like that isn't possible, you can make it so the order cancels if they don't have enough slots. If you could implement something like this it would cut the time of quick buying to a tenth of what it was before and it would be AMAZING. Thanks so much!

**Comment by jakemaguy** [comment]
Thanks for opening the suggestion.

Thats a great idea.  I will work on implementing that.

**Comment by jakemaguy** [comment]
The feature was added.  You can purchase multiple items like so:
- ```buy 4 shov``` to buy 4 shovels
-  ```buy 3 walk``` to buy 3 walkies

If your inventory is full, it will place them on the ground near your feet.  There may be some weird clipping depending on where you put the terminal in the ship.  If there's any more issues lmk.

**Comment by jakemaguy** [comment]
Upgrade to version ```1.1.0``` when it uploads to thunderstore
