### ISSUE TITLE
Conflict with Updated ReservedSlotCore 2.0+/HotBarPlus 1.5.2?+ mod(s) by flipMods

### ISSUE THREAD

**Issue by OldManLiver** [jakemaguy/QuickBuyMenu#19]
Last week (12-March-24) the ReservedItemSlotCore and Reserved Slot mods associated with it where updated to 2.0 . The subsequent updates have changed the API and added a few new features. Using hotbarplus by same developer in conjunction with the above and QuickBuyMenu created some conflicts. first incident occurred when attempting to purchase a shotgun through the "buy" command line. it resulted in the shotgun appearing in the 1st & 2nd inventory slots as well as in the reservedweaponslot, but the slots still acted like they where empty. while troubleshooting the issue, it was discovered that i could load a shotgun shell in the item i had in the reserved utility slot (which was rather disconcerting since  it was a Portable teleporter from LGU)
unity log during purchase of shotgun as follows:

[Info   : Unity Log] Set interminalmenu to true: True
[Info   :Configurable Company Variables] Terminal::TextPostProcess [Prefix]
[Error  : Unity Log] Trying to add Caret (TMPro.TMP_SelectionCaret) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.
[Warning:SimpleCommand.API] buy already exists as a default terminal keyword. This might cause issues.
[Warning: Unity Log] PlayOneShot was called with a null AudioClip.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ShotgunItem.StopUsingGun () (at <af9b1eec498a45aebd42601d6ab85015>:IL_0000)
ShotgunItem.PocketItem () (at <af9b1eec498a45aebd42601d6ab85015>:IL_0006)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::SwitchToItemSlot>(GameNetcodeStuff.PlayerControllerB,int,GrabbableObject)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::GrabObjectClientRpc>(GameNetcodeStuff.PlayerControllerB,bool,Unity.Netcode.NetworkObjectReference)
GameNetcodeStuff.PlayerControllerB.__rpc_handler_2552479808 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <af9b1eec498a45aebd42601d6ab85015>:IL_0064)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendClientRpc(FastBufferWriter&, UInt32, ClientRpcParams, RpcDelivery)
GameNetcodeStuff.PlayerControllerB:DMD<GameNetcodeStuff.PlayerControllerB::GrabObjectClientRpc>(PlayerControllerB, Boolean, NetworkObjectReference)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:GrabObjectSyncServerRpc(UInt64, NetworkObjectReference)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:__rpc_handler_2303539470(NetworkBehaviour, FastBufferReader, __RpcParams)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:GrabObjectSyncServerRpc(UInt64, NetworkObjectReference)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:EventClientRpc(UInt64, NetworkObjectReference, ClientRpcParams)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:__rpc_handler_1911613558(NetworkBehaviour, FastBufferReader, __RpcParams)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendClientRpc(FastBufferWriter&, UInt32, ClientRpcParams, RpcDelivery)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:EventClientRpc(UInt64, NetworkObjectReference, ClientRpcParams)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:EventServerRpc(Int32, UInt64, Int32, ServerRpcParams)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:__rpc_handler_2773582618(NetworkBehaviour, FastBufferReader, __RpcParams)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:EventServerRpc(Int32, UInt64, Int32, ServerRpcParams)
QuickBuyMenu.Plugin:RunQuickBuy(Terminal)
SimpleCommand.API.Patches.SimpleCommandPatches:PatchSubmit(Terminal&)
Terminal:DMD<Terminal::OnSubmit>(Terminal)
UnityEngine.Events.UnityEvent`1:Invoke(String)
TMPro.TMP_InputField:SendOnEndEdit()
TMPro.TMP_InputField:ReleaseSelection()
TMPro.TMP_InputField:DeactivateInputField(Boolean)
TMPro.TMP_InputField:OnUpdateSelected(BaseEventData)
UnityEngine.EventSystems.EventSystem:Update()

[Warning: Unity Log] PlayOneShot was called with a null AudioClip.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ShotgunItem.StopUsingGun () (at <af9b1eec498a45aebd42601d6ab85015>:IL_0000)
ShotgunItem.PocketItem () (at <af9b1eec498a45aebd42601d6ab85015>:IL_0006)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::SwitchToItemSlot>(GameNetcodeStuff.PlayerControllerB,int,GrabbableObject)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::GrabObjectClientRpc>(GameNetcodeStuff.PlayerControllerB,bool,Unity.Netcode.NetworkObjectReference)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler.GrabObjectSyncServerRpc (System.UInt64 clientId, Unity.Netcode.NetworkObjectReference obj) (at <fbf25d43353f4dc38b1ede6bf643fe65>:IL_0131)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler.__rpc_handler_2303539470 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <fbf25d43353f4dc38b1ede6bf643fe65>:IL_0056)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:GrabObjectSyncServerRpc(UInt64, NetworkObjectReference)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:EventClientRpc(UInt64, NetworkObjectReference, ClientRpcParams)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:__rpc_handler_1911613558(NetworkBehaviour, FastBufferReader, __RpcParams)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendClientRpc(FastBufferWriter&, UInt32, ClientRpcParams, RpcDelivery)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:EventClientRpc(UInt64, NetworkObjectReference, ClientRpcParams)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:EventServerRpc(Int32, UInt64, Int32, ServerRpcParams)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:__rpc_handler_2773582618(NetworkBehaviour, FastBufferReader, __RpcParams)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:EventServerRpc(Int32, UInt64, Int32, ServerRpcParams)
QuickBuyMenu.Plugin:RunQuickBuy(Terminal)
SimpleCommand.API.Patches.SimpleCommandPatches:PatchSubmit(Terminal&)
Terminal:DMD<Terminal::OnSubmit>(Terminal)
UnityEngine.Events.UnityEvent`1:Invoke(String)
TMPro.TMP_InputField:SendOnEndEdit()
TMPro.TMP_InputField:ReleaseSelection()
TMPro.TMP_InputField:DeactivateInputField(Boolean)
TMPro.TMP_InputField:OnUpdateSelected(BaseEventData)
UnityEngine.EventSystems.EventSystem:Update()

[Warning: Unity Log] PlayOneShot was called with a null AudioClip.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ShotgunItem.StopUsingGun () (at <af9b1eec498a45aebd42601d6ab85015>:IL_0000)
ShotgunItem.PocketItem () (at <af9b1eec498a45aebd42601d6ab85015>:IL_0006)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::SwitchToItemSlot>(GameNetcodeStuff.PlayerControllerB,int,GrabbableObject)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::GrabObjectClientRpc>(GameNetcodeStuff.PlayerControllerB,bool,Unity.Netcode.NetworkObjectReference)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler.GrabObjectSyncServerRpc (System.UInt64 clientId, Unity.Netcode.NetworkObjectReference obj) (at <fbf25d43353f4dc38b1ede6bf643fe65>:IL_0131)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler.EventClientRpc (System.UInt64 clientId, Unity.Netcode.NetworkObjectReference obj, Unity.Netcode.ClientRpcParams clientRpcParams) (at <fbf25d43353f4dc38b1ede6bf643fe65>:IL_01F5)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler.__rpc_handler_1911613558 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <fbf25d43353f4dc38b1ede6bf643fe65>:IL_0060)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendClientRpc(FastBufferWriter&, UInt32, ClientRpcParams, RpcDelivery)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:EventClientRpc(UInt64, NetworkObjectReference, ClientRpcParams)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:EventServerRpc(Int32, UInt64, Int32, ServerRpcParams)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:__rpc_handler_2773582618(NetworkBehaviour, FastBufferReader, __RpcParams)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
QuickBuyMenu.NetworkHandler.QuickBuyNetworkHandler:EventServerRpc(Int32, UInt64, Int32, ServerRpcParams)
QuickBuyMenu.Plugin:RunQuickBuy(Terminal)
SimpleCommand.API.Patches.SimpleCommandPatches:PatchSubmit(Terminal&)
Terminal:DMD<Terminal::OnSubmit>(Terminal)
UnityEngine.Events.UnityEvent`1:Invoke(String)
TMPro.TMP_InputField:SendOnEndEdit()
TMPro.TMP_InputField:ReleaseSelection()
TMPro.TMP_InputField:DeactivateInputField(Boolean)
TMPro.TMP_InputField:OnUpdateSelected(BaseEventData)
UnityEngine.EventSystems.EventSystem:Update()
 
![Screenshot 2024-03-17 135401](https://github.com/jakemaguy/QuickBuyMenu/assets/163762435/fe4e753a-7bbc-42f5-b384-1048bde895e8)

**Comment by jakemaguy** [comment]
I'm currently working on a fix for this.  I never tested with the buyable shotgun mod and there's some patching that I need to do in order to support the mod.  I have some unpushed changes just polishing a few things.
